package karl2d

when ODIN_OS == .Windows {
	DEFAULT_WINDOW_INTERFACE :: WINDOW_INTERFACE_WIN32
} else when ODIN_OS == .JS {
	DEFAULT_WINDOW_INTERFACE :: WINDOW_INTERFACE_JS
} else when ODIN_OS == .Linux {
	DEFAULT_WINDOW_INTERFACE :: WINDOW_INTERFACE_X11
} else when ODIN_OS == .Darwin {
	DEFAULT_WINDOW_INTERFACE :: WINDOW_INTERFACE_GLFW
}

WINDOW_INTERFACE :: DEFAULT_WINDOW_INTERFACE
